import {array, boolean, field, maybe, number, string, succeed} from "jsonous";

const userDetails = succeed({})
    .assign('email', field('email', string))
    .assign('phone', field('phone', string))
    .assign('phoneCountryCode', field('phoneCountryCode', string))
    .assign('position', field('position', maybe(string)))
    .assign('departmentName', field('departmentName', string))
    .assign('avatar', field('avatar', string))
    .assign('preferredLanguage', field('preferredLanguage', number))

const day = succeed({})
    .assign('from', field('from', string))
    .assign('to', field('to', string))

const schedule = succeed({})
    .assign('monday', field('monday', array(day)))
    .assign('tuesday', field('tuesday', array(day)))
    .assign('wednesday', field('wednesday', array(day)))
    .assign('thursday', field('thursday', array(day)))
    .assign('friday', field('friday', array(day)))
    .assign('saturday', field('saturday', array(day)))
    .assign('sunday', field('sunday', array(day)))

const ReservationDecoder = succeed({})
    .assign("userName", field("userName", string))
    .assign("userDetails", field("userDetails", userDetails ))
    .assign("workplaceName", field("workplaceName", string))
    .assign("comment", field("comment", maybe(string)))
    .assign("attributes", field("attributes", array(maybe(string))))
    .assign("from", field("from", string))
    .assign("to", field("to", string))
    .assign("cancelationAtTime", field("cancelationAtTime", string))
    .assign("schedule", field("schedule", schedule))
    .assign("maxBookingLength", field("maxBookingLength", maybe(string)))
    .assign("id", field("id", string))
    .assign("userId", field("userId", string ))
    .assign("workplaceId", field("workplaceId", string))
    .assign("workplaceType", field("workplaceType", number))
    .assign("title", field("title", string))
    .assign("status", field("status", number))
    .assign("station", field("station", string))
    .assign("address", field("address", string))
    .assign("guests", field("guests", array(maybe(string))))
    .assign("floorId", field("floorId", string))
    .assign("floorName", field("floorName", string))
    .assign("floorCode", field("floorCode", string))
    .assign("buildingId", field("buildingId", string))
    .assign("buildingName", field("buildingName", string))
    .assign("buildingCode", field("buildingCode", string))
    .assign("companyCode", field("companyCode", string))
    .assign("isCompleted", field("isCompleted", boolean))
    .assign("isFinished", field("isFinished", boolean))
    .assign("isCancelled", field("isCancelled", boolean))

export const getReservation = async (): Promise<any> => {
    const response = await window.fetch('../public/reservation.json');
    const data = await response.json()
    return ReservationDecoder.decodeAny(data)
};
